# Generated by Django 3.2.5 on 2024-07-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
