# Generated by Django 3.2.5 on 2024-07-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20240724_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
    ]
