# Generated by Django 3.2.5 on 2024-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_auto_20240715_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emailaddress',
            new_name='email',
        ),
    ]
