# Generated by Django 3.2.5 on 2024-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_class', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('parent_mobile_number', models.CharField(max_length=15)),
                ('current_status', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('passport', models.ImageField(blank=True, null=True, upload_to='passports/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
    ]
